version: 0.{build}

pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master

skip_tags: true

image: Visual Studio 2017
platform: x86
configuration: Release
clone_depth: 1

cache:
- C:\DLC\system
- C:\mod-manifest-gen.exe

init:
- ps: mkdir C:\DLC
- ps: Set-Content -Value "Name=Dreamcast DLCs`r`nDescription=Downloadable events from the Dreamcast version now on PC! This mod uses the SEGA/Sonic Team voice code by SonicFreak94.`r`nAuthor=PkR`r`nVersion=$env:APPVEYOR_BUILD_VERSION`r`nDLLFile=DLCs_Main.dll`r`nUpdateUrl=http://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/DLC`r`nChangelogUrl=http://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/DLC/Dreamcast DLC.txt" -Path C:\DLC\mod.ini
- cmd: cinst wget
- cmd: cd \
- cmd: wget -np --no-parent -nH --cut-dirs 4 -nc "https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Various/mod-manifest-gen.exe"
- cmd: wget -r -np --no-parent -nH --cut-dirs 4 -nc --reject htm,html,tmp,dll "https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/DLC/"
- cmd: cd C:\projects\sadx-dreamcast

before_build:
- cmd: git submodule update --init --recursive

build:
  project: DLCs_Main.sln
  
after_build:
- cmd: copy C:\projects\sadx-dreamcast-dlc\Release\DLCs_Main.dll C:\DLC\DLCs_Main.dll
- ps: $MyProcess = Start-Process "C:\mod-manifest-gen.exe" -Wait -PassThru -ArgumentList "C:\DLC"
- cmd: cd C:\DLC
- cmd: 7z a DLCs.7z *
- cmd: move DLCs.7z C:\projects\sadx-dreamcast-dlc\Release\DLCs.7z

artifacts:
- path: Release\DLCs.7z
